nodeLinker: node-modules
enableScripts: false
checksumBehavior: throw
enableImmutableInstalls: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: '@yarnpkg/plugin-allow-scripts'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

npmRegistries:
  'https://registry.npmjs.org':
    npmAlwaysAuth: false
